# [START cloudrun_mc_hello_php_nginx_serving_dockerfile]

# Context: ./

FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d

COPY index.php /var/www/html/index.php

# [END cloudrun_mc_hello_php_nginx_serving_dockerfile]
