assign_issues_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-sdk
- labels:
  - 'api: cloudiot'
  to:
  - laszlokorossy
- labels:
  - 'api: spanner'
  to:
  - shivgautam
- labels:
  - 'api: parametermanager'
  to:
  - GoogleCloudPlatform/cloud-parameters-team
- labels:
  - "api: modelarmor"
  to:
  - GoogleCloudPlatform/cloud-modelarmor-team

assign_prs_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-sdk
- labels:
  - 'api: cloudiot'
  to:
  - laszlokorossy
- labels:
  - 'api: parametermanager'
  to:
  - GoogleCloudPlatform/cloud-parameters-team
- labels:
  - "api: modelarmor"
  to:
  - GoogleCloudPlatform/cloud-modelarmor-team
