<?php
/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * DO NOT EDIT! This is a generated sample ("Request",  "job_search_create_client_event")
 */

// [START job_search_create_client_event]
require __DIR__ . '/vendor/autoload.php';

use Google\Cloud\Talent\V4beta1\EventServiceClient;
use Google\Cloud\Talent\V4beta1\ClientEvent;
use Google\Cloud\Talent\V4beta1\JobEvent;
use Google\Cloud\Talent\V4beta1\JobEvent_JobEventType;
use Google\Protobuf\Timestamp;

/**
 * Creates a client event.
 *
 * @param string $projectId Your Google Cloud Project ID
 * @param string $tenantId  Identifier of the Tenant
 * @param string $requestId A unique ID generated in the API responses.
 *                          Value should be set to the request_id from an API response.
 * @param string $eventId   A unique identifier, generated by the client application
 */
function sampleCreateClientEvent($projectId, $tenantId, $requestId, $eventId)
{
    // [START job_search_create_client_event_core]

    $eventServiceClient = new EventServiceClient();

    // $projectId = 'Your Google Cloud Project ID';
    // $tenantId = 'Your Tenant ID (using tenancy is optional)';
    // $requestId = '[request_id from ResponseMetadata]';
    // $eventId = '[Set this to a unique identifier]';
    $formattedParent = $eventServiceClient->tenantName($projectId, $tenantId);

    // The timestamp of the event as seconds of UTC time since Unix epoch
    // For more information on how to create google.protobuf.Timestamps
    // See: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto
    $seconds = 0;
    $createTime = new Timestamp();
    $createTime->setSeconds($seconds);

    // The type of event attributed to the behavior of the end user
    $type = JobEvent_JobEventType::VIEW;

    // List of job names associated with this event
    $jobsElement = 'projects/[Project ID]/tenants/[Tenant ID]/jobs/[Job ID]';
    $jobsElement2 = 'projects/[Project ID]/tenants/[Tenant ID]/jobs/[Job ID]';
    $jobs = [$jobsElement, $jobsElement2];
    $jobEvent = new JobEvent();
    $jobEvent->setType($type);
    $jobEvent->setJobs($jobs);
    $clientEvent = new ClientEvent();
    $clientEvent->setRequestId($requestId);
    $clientEvent->setEventId($eventId);
    $clientEvent->setCreateTime($createTime);
    $clientEvent->setJobEvent($jobEvent);

    try {
        $response = $eventServiceClient->createClientEvent($formattedParent, $clientEvent);
        printf('Created client event'.PHP_EOL);
    } finally {
        $eventServiceClient->close();
    }

    // [END job_search_create_client_event_core]
}
// [END job_search_create_client_event]

$opts = [
    'project_id::',
    'tenant_id::',
    'request_id::',
    'event_id::',
];

$defaultOptions = [
    'project_id' => 'Your Google Cloud Project ID',
    'tenant_id' => 'Your Tenant ID (using tenancy is optional)',
    'request_id' => '[request_id from ResponseMetadata]',
    'event_id' => '[Set this to a unique identifier]',
];

$options = getopt('', $opts);
$options += $defaultOptions;

$projectId = $options['project_id'];
$tenantId = $options['tenant_id'];
$requestId = $options['request_id'];
$eventId = $options['event_id'];

sampleCreateClientEvent($projectId, $tenantId, $requestId, $eventId);
